results_dir: ./results/

dataset: imagenet
tr_batch: 64
val_batch: 64
nworkers: 8

teachers:
  dinov2:
    backbone_type: dinov2_large
    checkpoint_path: pretrain/vfm/dinov2_vitl14_pretrain.bin
  clip:
    backbone_type: timmclip_large
    checkpoint_path: pretrain/vfm/vit_large_patch16_clip_336.bin
  sam:
    backbone_type: sam_large
    checkpoint_path: pretrain/vfm/samvit_large_patch16.bin
student:
  backbone:
    backbone_type: condition_moe_prism
    vit_name: vit_large
    down_ratio: 4
    aligner: True
    freeze_vit: False

    moe_type: gated
    router_type: no_structure_router
    gate_constraint_ranges: [ [ 0.5, 1.0 ],
                              [ 0.5, 1.0 ],
                              [ 0.5, 1.0 ],
                              [ 0.5, 1.0 ] ]
    condition_dim:
    num_moe_experts: 15
    moe_top_k: 3
    expert_hidden_ratio: 4.0

    moe_layers_indices: [ 5, 11, 17, 23 ]
    noisy_gating: True
    vfm_projection_configs:
    vfm_projector_type: mlp
    vit_checkpoint_path: pretrain/LL_s1.pth

    out_indices_cfg_for_task:
      small: [ 2, 5, 8, 11 ]
      base:  [2, 5, 8, 11]
      large: [ 5, 11, 17, 23 ]
      huge: [ 7, 15, 23, 31 ]
      giant: [ 9, 19, 29, 39 ]
      so: [ 6, 13, 20, 26 ]

    vit_type: conditioned_moe
teacher_output_indices:  [5, 11, 17, 23]
loss_type: cos+l1+decorrelation

max_epochs: 30
base_lr: 1e-3
weight_decay: 0.01
warmup_epochs: 2
grad_clip: 1.0
save_freq: 2
