results_dir: ./results/

dataset: pascalcontext
tr_batch:  3
val_batch: 8
nworkers: 2
task_dict:
  semseg: 1
  human_parts: 1
  normals: 1
  edge: 1
  sal: 1
teachers:
  dinov2:
    backbone_type: dinov2_large
    checkpoint_path: pretrain/vfm/dinov2_vitl14_pretrain.bin
    embed_dim: 1024
  clip:
    backbone_type: timmclip_large
    checkpoint_path: pretrain/vfm/vit_large_patch16_clip_336.bin
    embed_dim: 1024
  sam:
    backbone_type: sam_large
    checkpoint_path: pretrain/vfm/samvit_large_patch16.bin
    embed_dim: 1024
student:
  backbone:
    backbone_type: condition_moe_prism
    vit_name: vit_base
    vit_pretrained: False
    down_ratio: 4
    aligner: False
    freeze_vit: False

    moe_type: gated
    router_type: no_structure_router
    gate_constraint_ranges: [ [ 0.5, 1.0 ],
                              [ 0.5, 1.0 ],
                              [ 0.5, 1.0 ],
                              [ 0.5, 1.0 ] ]

    condition_dim:
    num_moe_experts: 15
    expert_hidden_ratio: 4.0
    moe_top_k: 3
    moe_layers_indices: [2, 5, 8, 11]
    noisy_gating: True
    vfm_projection_configs:
    vfm_projector_type: mlp
    vit_checkpoint_path:
    vfm_training: True
    out_indices_cfg_for_task:
      small: [ 2, 5, 8, 11 ]
      base:  [2, 5, 8, 11]
      large: [ 5, 11, 17, 23 ]
      huge: [ 7, 15, 23, 31 ]
      giant: [ 9, 19, 29, 39 ]
      so: [ 6, 13, 20, 26 ]
    vit_type: conditioned_moe

teacher_output_indices:  [5, 11, 17, 23]
loss_type: cos+l1+decorrelation
max_epochs: 50
max_iters: 40000
eval_freq: 2
base_lr: 2e-5
weight_decay: 1e-6
grad_clip: 10
